### ISSUE TITLE
PROJECT PORTAL - A Class Building

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#237]
### Insert Information
- [x] Insert Photos into Social Media Project
- [x] Insert Finalised Internal Sign Up Form
- [x] Insert Sales Contact Number

### Link
- [x] Link External Sign-up Form
- [x] Link clients website
- [x] Link Facebook Page #230 
- [x] Link Tumblr page #228 
- [x] Link eBrochure #233  
- [x] Link eNewsletter #229  
- [x] Link Qualify Questionnaire #235

**Comment by LiamAssetBuilders** [comment]
All links added to member details.
