### ISSUE TITLE
= STRATEGIC REVIEW CHECKLIST - BUSINESS MANAGERS=

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#287]
= STRATEGIC REVIEW CHECKLIST - BUSINESS MANAGERS=
 - [x] Facebook personal profile (if required)
 - [x] Facebook Business page (if required)
 - [x] Tumblr account web
 - [x] Instragram mobile app
 - [ ] Make sure you copy the Instagram Name into the Milestone
 - [ ] Add the  sign up form to your tablet device (optional)
 - [x] The next steps are crucial,
    - [x] Link your Instagram account to facebook and tumblr
    - [x] Make your first post ( we can delete this later)
    - [x] Add the sign up form to the home screen on your smart phone
    - [x] I will also need to take your photo, this will appear in the corner of your eNewsletter.
