### ISSUE TITLE
Strategic Review Checklist - Business Managers - National Luxury Homes

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#324]
- Assign to BM
 - [ ] Facebook personal profile (if required)
 - [ ] Facebook Business page (if required)
 - [ ] Tumblr account web
 - [ ] Instragram mobile app
 - [ ] Make sure you copy the Instagram Name into the Milestone
 - [ ] Add the  sign up form to your tablet device (optional)
 - [ ] The next steps are crucial,
    - [ ] Link your Instagram account to facebook and tumblr
    - [ ] Make your first post ( we can delete this later)
    - [ ] Add the sign up form to the home screen on your smart phone
    - [ ] I will also need to take your photo, this will appear in the corner of your eNewsletter.
- [ ] Acknowledge verification email for facebook
- [ ] Acknowledge verification email for facebook.
